"""empty message

Revision ID: 15ec2da256e7
Revises: 
Create Date: 2022-03-17 15:19:51.243105

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '15ec2da256e7'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Customer_Accounts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('firstname', sa.String(length=80), nullable=True),
    sa.Column('lastname', sa.String(length=80), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('password', sa.String(length=400), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('customerid', sa.Integer(), nullable=True),
    sa.Column('eventType', sa.String(length=80), nullable=True),
    sa.Column('session', sa.String(length=80), nullable=True),
    sa.Column('eventStatus', sa.String(length=80), nullable=True),
    sa.Column('eventDate', sa.String(length=80), nullable=True),
    sa.Column('eventTime', sa.String(length=80), nullable=True),
    sa.Column('expectGuestCount', sa.Integer(), nullable=True),
    sa.Column('tableCount', sa.Integer(), nullable=True),
    sa.Column('specialRequests', sa.String(length=80), nullable=True),
    sa.Column('phonenumber', sa.String(length=80), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('events')
    op.drop_table('Customer_Accounts')
    # ### end Alembic commands ###
