"""empty message

Revision ID: 35357a6c269a
Revises: 
Create Date: 2022-04-08 15:30:04.160302

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '35357a6c269a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('customerid', sa.Integer(), nullable=True),
    sa.Column('eventType', sa.String(length=80), nullable=True),
    sa.Column('session', sa.String(length=80), nullable=True),
    sa.Column('eventStatus', sa.String(length=80), nullable=True),
    sa.Column('eventDate', sa.String(length=80), nullable=True),
    sa.Column('eventTime', sa.String(length=80), nullable=True),
    sa.Column('expectGuestCount', sa.Integer(), nullable=True),
    sa.Column('tableCount', sa.Integer(), nullable=True),
    sa.Column('specialRequests', sa.String(length=1000), nullable=True),
    sa.Column('phonenumber', sa.String(length=80), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('events')
    # ### end Alembic commands ###
