"""empty message

Revision ID: 5646d3d43194
Revises: 3e8c2601bab5
Create Date: 2022-04-11 22:38:20.984632

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5646d3d43194'
down_revision = '3e8c2601bab5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('order',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('customerid', sa.String(length=80), nullable=True),
    sa.Column('itemid', sa.String(length=80), nullable=True),
    sa.Column('itemname', sa.String(length=80), nullable=True),
    sa.Column('itemtype', sa.String(length=80), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=True),
    sa.Column('price', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('events', sa.Column('eventtype', sa.String(length=80), nullable=True))
    op.add_column('events', sa.Column('eventstatus', sa.String(length=80), nullable=True))
    op.add_column('events', sa.Column('eventdate', sa.String(length=80), nullable=True))
    op.add_column('events', sa.Column('eventtime', sa.String(length=80), nullable=True))
    op.add_column('events', sa.Column('expectguestCount', sa.Integer(), nullable=True))
    op.add_column('events', sa.Column('tablecount', sa.Integer(), nullable=True))
    op.add_column('events', sa.Column('specialrequests', sa.String(length=1000), nullable=True))
    op.drop_column('events', 'eventStatus')
    op.drop_column('events', 'eventType')
    op.drop_column('events', 'specialRequests')
    op.drop_column('events', 'eventTime')
    op.drop_column('events', 'tableCount')
    op.drop_column('events', 'eventDate')
    op.drop_column('events', 'expectGuestCount')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('events', sa.Column('expectGuestCount', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('events', sa.Column('eventDate', sa.VARCHAR(length=80), autoincrement=False, nullable=True))
    op.add_column('events', sa.Column('tableCount', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('events', sa.Column('eventTime', sa.VARCHAR(length=80), autoincrement=False, nullable=True))
    op.add_column('events', sa.Column('specialRequests', sa.VARCHAR(length=1000), autoincrement=False, nullable=True))
    op.add_column('events', sa.Column('eventType', sa.VARCHAR(length=80), autoincrement=False, nullable=True))
    op.add_column('events', sa.Column('eventStatus', sa.VARCHAR(length=80), autoincrement=False, nullable=True))
    op.drop_column('events', 'specialrequests')
    op.drop_column('events', 'tablecount')
    op.drop_column('events', 'expectguestCount')
    op.drop_column('events', 'eventtime')
    op.drop_column('events', 'eventdate')
    op.drop_column('events', 'eventstatus')
    op.drop_column('events', 'eventtype')
    op.drop_table('order')
    # ### end Alembic commands ###
