"""empty message

Revision ID: 6918a02b6f11
Revises: 1db3e53fa1bb
Create Date: 2022-04-10 00:23:53.212797

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6918a02b6f11'
down_revision = '1db3e53fa1bb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('menu', 'itemDisclaimers')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('menu', sa.Column('itemDisclaimers', sa.VARCHAR(length=1000), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
