"""empty message

Revision ID: c59bb4f64789
Revises: 6918a02b6f11
Create Date: 2022-04-10 10:24:27.512428

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c59bb4f64789'
down_revision = '6918a02b6f11'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('menu',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('itemType', sa.String(length=80), nullable=True),
    sa.Column('itemTitle1', sa.String(length=200), nullable=True),
    sa.Column('itemTitle2', sa.String(length=200), nullable=True),
    sa.Column('itemPrice1', sa.Integer(), nullable=True),
    sa.Column('itemPrice2', sa.Integer(), nullable=True),
    sa.Column('itemDiscription', sa.String(length=1000), nullable=True),
    sa.Column('itemAdditionalDetails', sa.String(length=1000), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('menu')
    # ### end Alembic commands ###
