"""empty message

Revision ID: e6687b6da32e
Revises: 9afdfd8933a1
Create Date: 2022-04-12 20:38:12.269802

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e6687b6da32e'
down_revision = '9afdfd8933a1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('reservations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('customerid', sa.Integer(), nullable=True),
    sa.Column('reservationstype', sa.String(length=80), nullable=True),
    sa.Column('session', sa.String(length=80), nullable=True),
    sa.Column('reservationsstatus', sa.String(length=80), nullable=True),
    sa.Column('reservationsdate', sa.String(length=80), nullable=True),
    sa.Column('reservationstime', sa.String(length=80), nullable=True),
    sa.Column('expectguestCount', sa.Integer(), nullable=True),
    sa.Column('tablecount', sa.Integer(), nullable=True),
    sa.Column('specialrequests', sa.String(length=1000), nullable=True),
    sa.Column('phonenumber', sa.String(length=80), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('events')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('events',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('customerid', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('eventtype', sa.VARCHAR(length=80), autoincrement=False, nullable=True),
    sa.Column('session', sa.VARCHAR(length=80), autoincrement=False, nullable=True),
    sa.Column('eventstatus', sa.VARCHAR(length=80), autoincrement=False, nullable=True),
    sa.Column('eventdate', sa.VARCHAR(length=80), autoincrement=False, nullable=True),
    sa.Column('eventtime', sa.VARCHAR(length=80), autoincrement=False, nullable=True),
    sa.Column('expectguestCount', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('tablecount', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('specialrequests', sa.VARCHAR(length=1000), autoincrement=False, nullable=True),
    sa.Column('phonenumber', sa.VARCHAR(length=80), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='events_pkey')
    )
    op.drop_table('reservations')
    # ### end Alembic commands ###
